name: .NET Core

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: src/Feller

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.working-directory}}
    
    - name: Install GPR
      run: dotnet tool install gpr --global
      
    - name: GPR Package Upload
      run: find -name "*.nupkg" -print -exec gpr push -k ${{secrets.GH_PACKAGE}} {} \;
      
    - name: NuGet Package Upload
      if: github.ref == 'refs/heads/master'
      run: dotnet nuget push ${{env.working-directory}}/Feller/bin/Release/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET }} --source https://api.nuget.org/v3/index.json
